"""Exports a per-sensor "how much does this sensor pull on the network" table from a trained
CarAgent.onnx checkpoint, for the live in-Unity sensor-influence overlay.

Why this is a Python/offline step, not something computed live in Unity: it needs the raw first
Dense-layer weight matrix out of the ONNX graph, which the project's Unity Inference Engine
(com.unity.ai.inference) integration doesn't expose - this reads the .onnx file directly with the
`onnx` package instead (already available locally), once per checkpoint you want to inspect, and
writes a small JSON table Unity loads and looks up at runtime (SensorWeightOverlay.cs).

The metric: each fan sensor point contributes exactly 5 observation floats - a one-hot over
TileType (see carAgent.cs's AddTileOneHot / CollectObservations, "sensor readings: carSensor.
SensorCount x 5 values") - starting right after a fixed 17-float preamble (goal/velocity/steering/
current-tile state), so sensor i's block sits at input indices [17+5i, 17+5i+4]. Observations are
normalized before the first Dense layer (see the ONNX graph's Sub/Div/Clip nodes -
clip((x - running_mean) / running_std, -5, 5)), which matters here: a one-hot dim's INACTIVE (0)
state does NOT become exactly 0 after that affine transform (running_mean is rarely exactly 0), so
naively taking the weight-column norm of just the "active" dimension is wrong - both active and
inactive states of every one-hot dim contribute, just by different (precomputable, fixed) amounts.

For each sensor i and each HYPOTHESIZED currently-sensed tile type h (0..4, matching TileType.cs's
enum order exactly - Slippery/SpeedLimited/Terminal/Asphalt/Gravel):
    1. Build the 5-float one-hot the sensor would report if h is what's currently sensed.
    2. Normalize it the same way the exported graph does (clip((x-mean)/std, -5, 5)).
    3. contribution_vector = sum over the 5 dims of (normalized_value_j * W[:, dim_j])  (128-wide)
    4. effect(i, h) = L2 norm of contribution_vector - this sensor's total pull on the first
       hidden layer's 128 units, given it's currently sensing tile type h.
This is entirely determined by the checkpoint's own weights/normalizer stats (no live observation
needed to compute it) - so it can be precomputed once per checkpoint into a small (sensor_count x 5)
table, and the live Unity side just looks up table[sensor_index, current_tile_type] every frame
using CarSensor.readings (already computed every step) - no runtime ONNX/weight access needed there.

Caveat: this measures each sensor's DIRECT pull on the first hidden layer only, not how that signal
is then gated/combined through the rest of the network into the final action - a first-order
approximation of "how much does the network listen to this input," not true end-to-end sensitivity.

Usage:
    python export_sensor_weights.py --checkpoint path/to/CarAgent-19999982.onnx
        (writes path/to/CarAgent-19999982.sensor_weights.json by default)
    python export_sensor_weights.py --checkpoint path/to/CarAgent-19999982.onnx --out custom.json
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np
import onnx
from onnx import numpy_helper

PREAMBLE_SIZE = 17  # see carAgent.cs CollectObservations - fixed obs floats before the sensor block
FLOATS_PER_SENSOR = 5  # one-hot over TileType (Slippery/SpeedLimited/Terminal/Asphalt/Gravel)
NUM_TILE_TYPES = 5
CLIP_RANGE = 5.0  # matches the exported graph's normalizer Clip node (min=-5, max=5)

FIRST_LAYER_WEIGHT_NAME = "network_body._body_endoder.seq_layers.0.weight"  # shape (hidden, input)
NORMALIZER_MEAN_NAME = "network_body.observation_encoder.processors.0.normalizer.running_mean"
# The Div node's second input holds the running std - its initializer name is autogenerated by the
# ONNX exporter (e.g. "onnx::Div_86") and isn't stable across export versions, so it's resolved by
# walking the graph for the normalizer's Div node instead of hardcoding it (see resolve_std_name).


def resolve_std_initializer_name(graph) -> str:
    for node in graph.node:
        if node.op_type == "Div" and "normalizer" in node.name:
            return node.input[1]
    raise RuntimeError(
        "Could not find the normalizer's Div node in the ONNX graph - either this checkpoint was "
        "exported with normalize=false (car_agent.yaml's network_settings.normalize), or the "
        "ML-Agents export graph shape has changed. Inspect the graph with onnx.load(...).graph.node "
        "and update this script's normalizer-node lookup accordingly."
    )


def export_sensor_weights(checkpoint_path: Path) -> dict:
    model = onnx.load(str(checkpoint_path))
    graph = model.graph
    initializers = {init.name: numpy_helper.to_array(init) for init in graph.initializer}

    if FIRST_LAYER_WEIGHT_NAME not in initializers:
        raise RuntimeError(
            f"Expected first-layer weight initializer '{FIRST_LAYER_WEIGHT_NAME}' not found in "
            f"{checkpoint_path}. Available 2D initializers: "
            f"{[n for n, a in initializers.items() if a.ndim == 2]}. The ML-Agents export naming "
            "may have changed - update FIRST_LAYER_WEIGHT_NAME at the top of this script."
        )
    W = initializers[FIRST_LAYER_WEIGHT_NAME]  # (hidden_units, input_dim), e.g. (128, 137)
    hidden_units, input_dim = W.shape

    if NORMALIZER_MEAN_NAME not in initializers:
        raise RuntimeError(
            f"Expected normalizer mean '{NORMALIZER_MEAN_NAME}' not found - this checkpoint may "
            "have been trained with network_settings.normalize=false, in which case there's no "
            "normalizer to account for; adjust this script to skip the normalize step in that case."
        )
    mean = initializers[NORMALIZER_MEAN_NAME]
    std_name = resolve_std_initializer_name(graph)
    if std_name not in initializers:
        raise RuntimeError(f"Resolved std initializer name '{std_name}' not found among initializers.")
    std = initializers[std_name]

    sensor_count = (input_dim - PREAMBLE_SIZE) // FLOATS_PER_SENSOR
    expected_input_dim = PREAMBLE_SIZE + sensor_count * FLOATS_PER_SENSOR
    if expected_input_dim != input_dim:
        raise RuntimeError(
            f"input_dim={input_dim} doesn't decompose evenly into {PREAMBLE_SIZE} preamble floats "
            f"+ N*{FLOATS_PER_SENSOR} sensor floats - carAgent.cs's observation layout may have "
            "changed since this script was written (check CollectObservations)."
        )

    table = np.zeros((sensor_count, NUM_TILE_TYPES), dtype=np.float64)
    for i in range(sensor_count):
        base = PREAMBLE_SIZE + i * FLOATS_PER_SENSOR
        cols = W[:, base : base + FLOATS_PER_SENSOR]  # (hidden_units, 5)
        dim_mean = mean[base : base + FLOATS_PER_SENSOR]
        dim_std = std[base : base + FLOATS_PER_SENSOR]
        for h in range(NUM_TILE_TYPES):
            raw = np.zeros(FLOATS_PER_SENSOR, dtype=np.float64)
            raw[h] = 1.0
            normalized = np.clip((raw - dim_mean) / dim_std, -CLIP_RANGE, CLIP_RANGE)
            contribution = cols @ normalized  # (hidden_units,)
            table[i, h] = float(np.linalg.norm(contribution))

    return {
        "checkpoint": checkpoint_path.name,
        "sensor_count": sensor_count,
        "num_tile_types": NUM_TILE_TYPES,
        "hidden_units": hidden_units,
        "max_value": float(table.max()),
        # Flat row-major (sensor-major) array - Unity's JsonUtility can't parse nested arrays-of-
        # arrays cleanly, so values[i * num_tile_types + h] is sensor i / tile type h.
        "values": table.flatten().tolist(),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--checkpoint", required=True, help="Path to a CarAgent-<step>.onnx checkpoint.")
    ap.add_argument("--out", default=None,
                     help="Output JSON path (default: <checkpoint>.sensor_weights.json next to it).")
    args = ap.parse_args()

    checkpoint_path = Path(args.checkpoint)
    if not checkpoint_path.is_file():
        print(f"Checkpoint not found: {checkpoint_path}", file=sys.stderr)
        sys.exit(1)
    out_path = Path(args.out) if args.out else checkpoint_path.with_suffix("").with_suffix(".sensor_weights.json")

    result = export_sensor_weights(checkpoint_path)
    with open(out_path, "w") as f:
        json.dump(result, f, indent=1)
    print(f"sensor_count={result['sensor_count']} hidden_units={result['hidden_units']} "
          f"max_value={result['max_value']:.4f}")
    print(f"Wrote -> {out_path}")


if __name__ == "__main__":
    main()
