using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Unity.MLAgents;
using Unity.MLAgents.Policies;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

// Writes build_info.txt next to every Standalone build, so a build sitting in an HPC folder is
// self-documenting (sensor shape/points, observation size, action space) instead of relying on
// memory of "which build is this." Cat this file into your job script's .out header alongside
// the existing "Run: ..." line - see the comment at the bottom for the exact shell snippet.
public static class BuildInfoWriter
{
    // Both the legacy [PostProcessScene] attribute and the newer IProcessSceneWithReport
    // interface were tried here first and NEITHER ever fired under this project's Unity 6/URP
    // build pipeline - confirmed by diagnostic Debug.Log calls in both that never printed, even
    // though OnPostprocessBuild below (a normal per-build, not per-scene, callback) fired fine
    // every time. Rather than chase why the per-scene hook is skipped, this sidesteps it
    // entirely: by the time OnPostprocessBuild runs the build has already finished, so it's safe
    // to just re-open every scene registered in Build Settings right here and scan it directly -
    // no dependency on any scene-processing callback timing/caching quirk at all.
    [PostProcessBuild(1)]
    public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
    {
        CarSensor sensor = null;
        BehaviorParameters behavior = null;
        CarAgent agent = null;
        car_component carController = null;
        GridManager gridManager = null;

        var openedPaths = new List<string>();

        Debug.Log($"[BuildInfoWriter] EditorBuildSettings.scenes has {EditorBuildSettings.scenes.Length} entries; " +
            $"{EditorSceneManager.sceneCount} scene(s) currently loaded.");

        foreach (var buildScene in EditorBuildSettings.scenes)
        {
            if (!buildScene.enabled)
            {
                Debug.Log($"[BuildInfoWriter] Skipping disabled scene '{buildScene.path}'.");
                continue;
            }

            bool alreadyLoaded = false;
            for (int i = 0; i < EditorSceneManager.sceneCount; i++)
            {
                if (EditorSceneManager.GetSceneAt(i).path == buildScene.path) { alreadyLoaded = true; break; }
            }

            Scene scene;
            if (!alreadyLoaded)
            {
                scene = EditorSceneManager.OpenScene(buildScene.path, OpenSceneMode.Additive);
                openedPaths.Add(buildScene.path);
            }
            else
            {
                scene = EditorSceneManager.GetSceneByPath(buildScene.path);
            }

            Debug.Log($"[BuildInfoWriter] Scene '{buildScene.path}': alreadyLoaded={alreadyLoaded}, " +
                $"isLoaded={scene.isLoaded}, isValid={scene.IsValid()}, rootCount={(scene.IsValid() ? scene.rootCount : -1)}");

            if (sensor == null) sensor = UnityEngine.Object.FindAnyObjectByType<CarSensor>(FindObjectsInactive.Include);
            if (behavior == null) behavior = UnityEngine.Object.FindAnyObjectByType<BehaviorParameters>(FindObjectsInactive.Include);
            if (agent == null) agent = UnityEngine.Object.FindAnyObjectByType<CarAgent>(FindObjectsInactive.Include);
            if (carController == null) carController = UnityEngine.Object.FindAnyObjectByType<car_component>(FindObjectsInactive.Include);
            if (gridManager == null) gridManager = UnityEngine.Object.FindAnyObjectByType<GridManager>(FindObjectsInactive.Include);

            Debug.Log($"[BuildInfoWriter] After scanning '{buildScene.path}': sensor={sensor != null}, " +
                $"behavior={behavior != null}, agent={agent != null}, car={carController != null}, grid={gridManager != null}");
        }

        var decisionRequester = agent != null ? agent.GetComponent<DecisionRequester>() : null;

        var sb = new StringBuilder();
        sb.AppendLine("=== Build info (auto-generated by BuildInfoWriter.cs) ===");
        sb.AppendLine($"Built: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Target: {target}, Unity {Application.unityVersion}");

        if (sensor != null)
        {
            sb.AppendLine($"Sensor shape: {sensor.sensorShape}, {sensor.SensorCount} points");
            sb.AppendLine($"Expected observation size (16 fixed + points*4 one-hot): {16 + sensor.SensorCount * 4}");
        }
        else
        {
            sb.AppendLine("Sensor shape: (no CarSensor found in the built scene)");
        }

        if (behavior != null)
        {
            var brain = behavior.BrainParameters;
            var actionSpec = brain.ActionSpec;
            string branches = actionSpec.BranchSizes != null && actionSpec.BranchSizes.Length > 0
                ? string.Join(",", actionSpec.BranchSizes)
                : "none";
            sb.AppendLine($"Configured Vector Observation Size: {brain.VectorObservationSize}");
            sb.AppendLine($"Actions: {actionSpec.NumContinuousActions} continuous, discrete branches [{branches}]");
        }
        else
        {
            sb.AppendLine("Actions: (no BehaviorParameters found in the built scene)");
        }

        if (agent != null)
            sb.AppendLine($"Agent Max Step: {agent.MaxStep}" +
                (decisionRequester != null ? $", Decision Period: {decisionRequester.DecisionPeriod}" : ""));

        if (carController != null)
        {
            sb.AppendLine($"Normal top speed: {carController.normalTopSpeedMS} m/s");
            sb.AppendLine($"SpeedLimited tile: {carController.grassSpeedFraction:P0} of top speed, " +
                $"brake torque {carController.speedLimitBrakeTorque}");
            sb.AppendLine($"Slippery tile: friction x{carController.slipperyFrictionMultiplier}, " +
                $"disturbance force {carController.slipperyDisturbanceForce} N / torque " +
                $"{carController.slipperyDisturbanceTorque} N·m every {carController.slipperyDisturbanceInterval}s");
        }
        else
        {
            sb.AppendLine("Tile physics: (no car_component found in the built scene)");
        }

        if (gridManager != null)
        {
            sb.AppendLine($"Grid: {gridManager.gridSize}x{gridManager.gridSize}, cell size {gridManager.cellSize}m, " +
                $"noise scale {gridManager.noiseScale}");
            sb.AppendLine($"Tile mix (raw weights, auto-normalized): Normal {gridManager.probNormal}, " +
                $"SpeedLimited {gridManager.probSpeedLimited}, Slippery {gridManager.probSlippery}, " +
                $"Terminal {gridManager.probTerminal}");
        }
        else
        {
            sb.AppendLine("Grid: (no GridManager found in the built scene)");
        }

        sb.AppendLine("--- NOT included here: reward weights, bootstrap curriculum, escalation settings ---");
        sb.AppendLine("--- Those come from environment_parameters in your YAML and can differ per run  ---");
        sb.AppendLine("--- even with this exact same build - check the run's own config, not this file. ---");
        sb.AppendLine("===========================================================");

        string outputDir = Path.GetDirectoryName(pathToBuiltProject);
        string manifestPath = Path.Combine(outputDir, "build_info.txt");
        File.WriteAllText(manifestPath, sb.ToString());
        Debug.Log($"[BuildInfoWriter] Wrote build manifest to {manifestPath}");

        // Close only the scenes we opened ourselves here, leaving whatever the user already had
        // open (and its dirty/undo state) untouched. Must happen AFTER the manifest string above
        // is fully built, not before - CloseScene destroys that scene's GameObjects, and Unity
        // overloads != null for destroyed objects to evaluate false, so every sensor/behavior/
        // agent/carController/gridManager reference above would silently read back as "not
        // found" if this ran any earlier, even though the scan itself (further up) found them
        // all just fine.
        for (int i = EditorSceneManager.sceneCount - 1; i >= 0; i--)
        {
            Scene scene = EditorSceneManager.GetSceneAt(i);
            if (openedPaths.Contains(scene.path))
                EditorSceneManager.CloseScene(scene, true);
        }
    }
}

// In your HPC job script, right next to the existing echo for the "Run: ..." header line:
//   cat /path/to/build_info.txt
// That prints it straight into the same .out file your job already redirects to.
