using System;
using System.IO;
using System.Text;
using Unity.MLAgents;
using Unity.MLAgents.Policies;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

// Writes build_info.txt next to every Standalone build, so a build sitting in an HPC folder is
// self-documenting (sensor shape/points, observation size, action space) instead of relying on
// memory of "which build is this." Cat this file into your job script's .out header alongside
// the existing "Run: ..." line - see the comment at the bottom for the exact shell snippet.
public static class BuildInfoWriter
{
    // [PostProcessBuild] only sees whatever scene(s) happen to already be loaded in the Editor
    // when the whole build finishes - not the scene(s) actually baked into the player - so
    // FindAnyObjectByType there can silently find nothing even though the build is fine (this is
    // what caused the "(no X found in the built scene)" gaps in some HPC build logs).
    // [PostProcessScene] instead fires once per scene *during* the build, while that scene is
    // genuinely loaded for processing, so it can't miss anything. It has no access to the output
    // path though, so it just stashes what it finds here; OnPostprocessBuild reads the stash and
    // does the actual file write once the build (and thus the output path) exists. A scene with
    // none of these components must not clobber a hit from an earlier scene in a multi-scene
    // build, hence the `??=`-style "only fill if still empty" checks.
    private static CarSensor foundSensor;
    private static BehaviorParameters foundBehavior;
    private static CarAgent foundAgent;
    private static car_component foundCarController;
    private static GridManager foundGridManager;

    [PostProcessScene]
    public static void OnPostprocessScene()
    {
        if (foundSensor == null) foundSensor = UnityEngine.Object.FindAnyObjectByType<CarSensor>();
        if (foundBehavior == null) foundBehavior = UnityEngine.Object.FindAnyObjectByType<BehaviorParameters>();
        if (foundAgent == null) foundAgent = UnityEngine.Object.FindAnyObjectByType<CarAgent>();
        if (foundCarController == null) foundCarController = UnityEngine.Object.FindAnyObjectByType<car_component>();
        if (foundGridManager == null) foundGridManager = UnityEngine.Object.FindAnyObjectByType<GridManager>();
    }

    [PostProcessBuild(1)]
    public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
    {
        var sensor = foundSensor;
        var behavior = foundBehavior;
        var agent = foundAgent;
        var decisionRequester = agent != null ? agent.GetComponent<DecisionRequester>() : null;
        var carController = foundCarController;
        var gridManager = foundGridManager;

        // Reset for the next build in this Editor session - these are static so they'd otherwise
        // leak a stale hit from this build into the next one.
        foundSensor = null;
        foundBehavior = null;
        foundAgent = null;
        foundCarController = null;
        foundGridManager = null;

        var sb = new StringBuilder();
        sb.AppendLine("=== Build info (auto-generated by BuildInfoWriter.cs) ===");
        sb.AppendLine($"Built: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Target: {target}, Unity {Application.unityVersion}");

        if (sensor != null)
        {
            sb.AppendLine($"Sensor shape: {sensor.sensorShape}, {sensor.SensorCount} points");
            sb.AppendLine($"Expected observation size (16 fixed + points*4 one-hot): {16 + sensor.SensorCount * 4}");
        }
        else
        {
            sb.AppendLine("Sensor shape: (no CarSensor found in the built scene)");
        }

        if (behavior != null)
        {
            var brain = behavior.BrainParameters;
            var actionSpec = brain.ActionSpec;
            string branches = actionSpec.BranchSizes != null && actionSpec.BranchSizes.Length > 0
                ? string.Join(",", actionSpec.BranchSizes)
                : "none";
            sb.AppendLine($"Configured Vector Observation Size: {brain.VectorObservationSize}");
            sb.AppendLine($"Actions: {actionSpec.NumContinuousActions} continuous, discrete branches [{branches}]");
        }
        else
        {
            sb.AppendLine("Actions: (no BehaviorParameters found in the built scene)");
        }

        if (agent != null)
            sb.AppendLine($"Agent Max Step: {agent.MaxStep}" +
                (decisionRequester != null ? $", Decision Period: {decisionRequester.DecisionPeriod}" : ""));

        if (carController != null)
        {
            sb.AppendLine($"Normal top speed: {carController.normalTopSpeedMS} m/s");
            sb.AppendLine($"SpeedLimited tile: {carController.grassSpeedFraction:P0} of top speed, " +
                $"brake torque {carController.speedLimitBrakeTorque}");
            sb.AppendLine($"Slippery tile: friction x{carController.slipperyFrictionMultiplier}, " +
                $"disturbance force {carController.slipperyDisturbanceForce} N / torque " +
                $"{carController.slipperyDisturbanceTorque} N·m every {carController.slipperyDisturbanceInterval}s");
        }
        else
        {
            sb.AppendLine("Tile physics: (no car_component found in the built scene)");
        }

        if (gridManager != null)
        {
            sb.AppendLine($"Grid: {gridManager.gridSize}x{gridManager.gridSize}, cell size {gridManager.cellSize}m, " +
                $"noise scale {gridManager.noiseScale}");
            sb.AppendLine($"Tile mix (raw weights, auto-normalized): Normal {gridManager.probNormal}, " +
                $"SpeedLimited {gridManager.probSpeedLimited}, Slippery {gridManager.probSlippery}, " +
                $"Terminal {gridManager.probTerminal}");
        }
        else
        {
            sb.AppendLine("Grid: (no GridManager found in the built scene)");
        }

        sb.AppendLine("--- NOT included here: reward weights, bootstrap curriculum, escalation settings ---");
        sb.AppendLine("--- Those come from environment_parameters in your YAML and can differ per run  ---");
        sb.AppendLine("--- even with this exact same build - check the run's own config, not this file. ---");
        sb.AppendLine("===========================================================");

        string outputDir = Path.GetDirectoryName(pathToBuiltProject);
        string manifestPath = Path.Combine(outputDir, "build_info.txt");
        File.WriteAllText(manifestPath, sb.ToString());
        Debug.Log($"[BuildInfoWriter] Wrote build manifest to {manifestPath}");
    }
}

// In your HPC job script, right next to the existing echo for the "Run: ..." header line:
//   cat /path/to/build_info.txt
// That prints it straight into the same .out file your job already redirects to.
